spring:
  profiles:
    active: dev
  application:
    name: registry
server:
  port: 8761

eureka:
  instance:
    hostname: registry
    preferIpAddress: true
    ipAddress: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ipAddress}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF


        